<style>
	#moreinfo {background:#333;color:#ccc;padding:0em;margin:0.7em;padding:0.1em 0.5em;}
	#moreinfo td {color:#ccc;padding:0.1em;}
	#moreinfo th {color:#fff;font-weight: bold;background:#555}
	#moreinfo h1 {font-size:2em;}
	#moreinfo h2 {font-size:1.5em;}
	#moreinfo p {padding-left:1em;}
	#moreinfo a {color:yellow;text-decoration: underline;}
	#moreinfo strong {color:#fcc}
</style>

<div id="moreinfo">
	<h2>Jména testovacích metod</h2>
	<p>Podtržítka jsou nahrazeny mezerami, je odstraněno první slovo "test".<br>
	Pokud je ve jméně obsažena <strong>hexadecimální entita</strong> 0x40, je převedena na odpovídající znak.<br>
	Pokud metoda končí na _1 (tedy podtržíťko následované číslem), je ve výpise uvedemo metoda (1)

		<table border=1>
			<tr><th>Znak</th><th>Kód</th></tr>
			<tr><th>:</th><td>0x3a</td></tr>
			<tr><th>(</th><td>0x28</td></tr>
			<tr><th>)</th><td>0x29</td></tr>
			<tr><th>[</th><td>0x5b</td></tr>
			<tr><th>]</th><td>0x5d</td></tr>
			<tr><th>=</th><td>0x3d</td></tr>
		</table>
		<a target="_blank" href="http://en.wikipedia.org/wiki/ASCII">Tabulka ascii znaků</a>
	</p>


</div>
