<style>
	#moreinfo {background:#333;color:#ccc;padding:0em;margin:0.7em;padding:0.1em 0.5em;}
	#moreinfo td {color:#ccc;padding:0.1em;}
	#moreinfo th {color:#fff;font-weight: bold;background:#555}
	#moreinfo h1 {font-size:2em;}
	#moreinfo h2 {font-size:1.5em;}
	#moreinfo p {padding-left:1em;}
	#moreinfo a {color:yellow;text-decoration: underline;}
	#moreinfo strong {color:#fcc}
	a.classname {font-family:consolas, courier, monospace; color:darkblue}
	a:hover {text-decoration: underline; color:blue}
	a:visited {color:darkblue;}
	.notrunned {color:#aaa;}
	.notrunned a.classname {color:#aaa}
	div.suitename {color:#555; padding:4px 0 1em 0;font-weight:bold;margin:0 0 0.5em 0;padding:0px;padding-bottom:2px;border-bottom:1px solid #eee;}
	div.filtername {color:#555; padding:4px 0 1em 0;font-weight:bold}
	div.filtername code {font-family:consolas; color:black;font-size:14px;background:#eee;padding:3px;}
	.inv {color:#aaa}
	.pree {font-family:consolas; font-size:10px;text-align:left;}
</style>

<div id="moreinfo">
	<h2>Jména testovacích metod</h2>
	<p>Podtržítka jsou nahrazeny mezerami, je odstraněno první slovo "test".<br>
	Pokud je ve jméně obsažena <strong>hexadecimální entita</strong> 0x40, je převedena na odpovídající znak.<br>
	Pokud metoda končí na _1 (tedy podtržíťko následované číslem), je ve výpise uvedemo metoda (1)

		<table border=1>
			<tr><th>Znak</th><th>Kód</th></tr>
			<tr><th>:</th><td>0x3a</td></tr>
			<tr><th>(</th><td>0x28</td></tr>
			<tr><th>)</th><td>0x29</td></tr>
			<tr><th>[</th><td>0x5b</td></tr>
			<tr><th>]</th><td>0x5d</td></tr>
			<tr><th>=</th><td>0x3d</td></tr>
		</table>
		<a target="_blank" href="http://en.wikipedia.org/wiki/ASCII">Tabulka ascii znaků</a>
	</p>


</div>
